### PR TITLE
Allow opening db multiple times in read only mode

### PR DESCRIPTION
**Pull request by sandreim**
We need this capability for monitoring db usage for paritydb enable nodes.

https://github.com/paritytech/polkadot-introspector/issues/107

### CODE REVIEW

**Comment by cheme** [comment]
I started thinking on how to implement it (wanted to try it this week but got delayed on other stuff).
Issue with having a node that read open file is that the file(s) may be in an incoherent state: some part written and not flushed, some over file written and not flush... So I fear just doing this will lead to the reading process potentially reading incoherent state.
To attach a reading access, I fear we need to share at least the log overlay cache (read node will be a bit behind but in a coherent state). This way we ensure the  state is in right state with a single commit.
But this means at least an ipc to send the commit numbers and do lock during update and log overlay cache memory shared. Or just ipc all items for the log overlay and duplicate the log overlay cache.

Maybe I overthink it and it can run this way (would need testing). CC\ @arkpar

**Comment by cheme** [comment]
@sandreim what are the operation the introspector needs to be able to do ? just peeking at https://github.com/paritytech/polkadot-introspector/blob/master/src/kvdb/paritydb.rs it gives me the feeling it expect iterator available (which is rarely the case for paritydb).

**Comment by sandreim** [comment]
Our usecase is just iterating and measuring key and value sizes. Doesn’t need to be 100% accurate wrt contents.

**Comment by cheme** [comment]
If implementing the read only access on a node open for writing, he introspector will only work with the following columns https://github.com/paritytech/polkadot/blob/5de9b7f6e5608c4e7ac91b9f241064e4fe48cb85/node/service/src/parachains_db/mod.rs#L40 .
For other column the introspector would need us to store things differently:
- attach key with values
- do full scan iteration of the column (even for a single prefix)
- iterate offline (we currently only iterate on non index column in migration process), or do the fullscan iteration over the node overlay to. This point is not a real blocker.

On a side note I remember seeing the need for read access in the context of substrate archive, so I think it could make sense to have it.

**Comment by vstakhov** [comment]
Another option is to have an iterator but return a hash instead of the key. It would be enough for our use cases (we just need db size in the majority of the cases). If we can get a size of DB per column somehow without iterating, I'm open for adding such an optimization here.

**Comment by arkpar** [comment]
Would simply adding the size of DB files on disk work? It is much faster than iterating and won't hinder the system IO.

**Comment by cheme** [comment]
We also can probably got column stats (I would read stats directly from the files (no db opening) in this case) when they are active.

**Comment by sandreim** [comment]
> We also can probably got column stats (I would read stats directly from the files (no db opening) in this case) when they are active.

I think this would do the job.

**Comment by sandreim** [comment]
> Would simply adding the size of DB files on disk work? It is much faster than iterating and won't hinder the system IO.

Can we compute the column sizes based on the file sizes? If so, then yeah this is a good alternative as well, but more error prone if on disk structure changes

**Comment by vstakhov** [comment]
> Would simply adding the size of DB files on disk work? It is much faster than iterating and won't hinder the system IO.

For now, we have 3 parameters per column:

* Keys count
* Keys size
* Values size

If we can have that from metadata, that would be great for these purposes. And it will be much faster than RocksDB option which is also good.

**Comment by arkpar** [comment]
We can add a function to estimate DB size based on the size of the index and value tables. This will give you total data size, but not the number of key-values. To get more detailed info, we can add a function to get stats without opening the database. However there's a couple of catches.
1. You would need to enable stat collection when opening the database for in your main process. This comes with small performance hit.
2. Stats are currently flushed only when closing the database.

Allowing opening a database for shared access as this PR currently tries to do is indeed pronce to misuse. As @cheme noticed we can't guarantee data consistency when another instance is writing.

**Comment by arkpar** [comment]
I'm closing this fo reasons listed in he [comment](https://github.com/paritytech/parity-db/pull/94#issuecomment-1245193637)

**Pull request closed without merging**
