### PR TITLE
Adds compression threshold to column options serialization

### PR DESCRIPTION
**Pull request by Tpt**

### CODE REVIEW

**Comment by arkpar** [comment]
It is omitted from serialization because it does not really affect how existing data is handled. Changing it does not break compatibility. I'd argue it should not even be in the metadata struct, but just in `ColumnOptions`. @cheme what do you think?

**Comment by cheme** [comment]
> It is omitted from serialization because it does not really affect how existing data is handled. Changing it does not break compatibility. I'd argue it should not even be in the metadata struct, but just in `ColumnOptions`. @cheme what do you think?

Yes, I agree, should be modifiable when we instantiate the db.

**Comment by Tpt** [comment]
Thank you for the review. My motivation for this change was to allow opening databases with non-default compression threshold. 

>  I'd argue it should not even be in the metadata struct, but just in ColumnOptions.

Ok! So we might need to have a `ColumnMetadata` struct that woud keep the fixed metadata (i.e. everything in `ColumnOptions` but `compression_threshold`). Am I correct?

**Comment by Tpt** [comment]
> I suggest simply moving `compression_threshold` from `ColumnOptions` to `Options` as a `HashMap<ColId, u32>`.

Done in #103

**Pull request closed without merging**
