### PR TITLE
Clean logs using the usual process even in case of replay or db failure

### LINKED ISSUE #145: After recovery on corrupted log, existing values might get overriden after unrelated commit processing
Senario:
1. The database is created with reference-counting.
2. A first commit C1 is done, inserting a key K1, the commit is processed and the log is flushed
3. A first commit C2 is done, inserting a key K2 is inserted, and the commit is processed.
4. A third commit C3 is done (might be empty), but the I/Os fail during commit processing.
5. The database is closed and open again. The second log file is invalid and removed.
6. The database is closed and open a second time. K1 is still present in the DB.
7. A fourth commit C4 is done and processed. When writing a `Key mismatch at 2` log is printed.
8. K1 is not in the database anymore.

As a test:
```rust
	#[test]
	fn test_from_fuzzer() {
		let tmp = tempdir().unwrap();
		let mut options = Options::with_columns(tmp.path(), 1);
		options.columns[0].ref_counted = true;
		options.columns[0].preimage = true;
		options.always_flush = true;
		options.with_background_thread = false;

		{
			let db = Db::open_or_create(&options).unwrap();
			db.commit_changes(vec![(0, Operation::Set(vec![59], vec![59]))]).unwrap();
			db.process_commits().unwrap();
			db.flush_logs().unwrap();
			db.commit_changes(vec![(0, Operation::Set(vec![0], vec![0]))]).unwrap();
			db.process_commits().unwrap();
			db.commit_changes(vec![]).unwrap();
			crate::set_number_of_allowed_io_operations(3);
			assert!(db.process_commits().is_err()); // Partial write
			crate::set_number_of_allowed_io_operations(usize::MAX);
		}

		{
			let db = Db::open(&options).unwrap();
			assert!(db.get(0, &[0]).unwrap().is_some()) // Key 0 is here
		}

		{
			let db = Db::open(&options).unwrap();
			assert!(db.get(0, &[0]).unwrap().is_some()); // Key 0 is here
			db.commit_changes(vec![(0, Operation::Set(vec![196], vec![196]))])
			.unwrap();
			db.process_commits().unwrap();
			assert!(db.get(0, &[0]).unwrap().is_none()) // Key 0 has been removed
		}
	}
```

Before C4 the database content is:
```
Index key: [22, 1f, f2, 5f, 13, 93, be, df, 22, cc, fd, 8e, 6b, 6b, bf, e1, bf, d6, 3f, 3c, 27, 2a, 9c, 1f, db, 53, be, a3, 18, 15, 32, e0]
        Rc: 1
Value: 3b
Index key: [f3, 71, 9b, 9e, 9f, be, 4, e3, 5f, 25, 5c, d7, a9, 29, c5, 24, d9, 8d, b1, 21, 19, 2f, 64, 6e, 52, c3, 3b, 9b, 1b, d8, 6d, 6f]
        Rc: 1
Value: 00
```

And after:
```
for 65536 chunks of column 0
Index key: [22, 1f, f2, 5f, 13, 93, be, df, 22, cc, fd, 8e, 6b, 6b, bf, e1, bf, d6, 3f, 3c, 27, 2a, 9c, 1f, db, 53, be, a3, 18, 15, 32, e0]
        Rc: 1
parity_db::column] Value: 3b
Index key: [a5, fa, ce, bb, 91, 75, b7, d7, c5, 4b, de, f6, 65, e1, a5, 2d, 82, b2, 29, 33, 2c, 60, ab, 29, ab, 57, 8, 15, b2, dc, c6, ed]
        Rc: 1
Value: c4
Index key: [f3, 71, 9b, 9e, 9f, be, b7, d7, c5, 4b, de, f6, 65, e1, a5, 2d, 82, b2, 29, 33, 2c, 60, ab, 29, ab, 57, 8, 15, b2, dc, c6, ed]
        Rc: 1
Value: c4
```

It seems like somehow the (0, 0) key-value partially overridden by the (196-196) key-value.

### PR DESCRIPTION
**Pull request by Tpt**
Closes #145

### CODE REVIEW

**Comment by Tpt** [comment]
* Applies @arkpar suggestion from #146
* No test yet because the test from #145 requires the intrumentation feature

**Review by arkpar — APPROVED** [review]

**Comment by Tpt** [comment]
@arkpar Thank you for your review. It seems I have forgotten to add an extra `kill_logs` in case  `replay_all_logs`  fails with an exception. I have pushed a commit to this PR to fix that.

**Comment by Tpt** [comment]
I have pushed a test.

Sadly it seems tha the fuzzer has found an other similar corruption bug during recovery. I'm currently investigating it. It might make sense to put this PR on hold for now.

**Comment by Tpt** [comment]
I have found the cause of the fuzzer error, it's the use case "the disk becames unreadable during recovery so the fuzzer model believes the database is empty. After the subsequence DB restart the recovery process works and past commits get properly reneacted, leading to a DB state different from the fuzzer model". I have opened #149 to fix it.

I have also pushed a commit that calls `clean_logs` before calling `kill_logs` on error. It allows to ensure logs are properly emptied before closing the database.

**Pull request merged**
